language: node_js
node_js:
  - '12'
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master
